# Generated by Django 5.2.5 on 2025-08-25 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Haupt-Organisator",
            ),
        ),
        migrations.CreateModel(
            name="EventOrganizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("moderator", "Moderator"),
                            ("assistant", "Assistent"),
                        ],
                        default="assistant",
                        max_length=20,
                        verbose_name="Rolle",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text="Liste der Berechtigungen für diesen Organisator",
                        verbose_name="Berechtigungen",
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Interne Notizen zu diesem Organisator",
                        verbose_name="Notizen",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_organizers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eingeladen von",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organisator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event-Organisator",
                "verbose_name_plural": "Event-Organisatoren",
                "ordering": ["role", "invited_at"],
                "unique_together": {("event", "user")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="organizers",
            field=models.ManyToManyField(
                blank=True,
                related_name="co_organized_events",
                through="events.EventOrganizer",
                through_fields=("event", "user"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="Alle Organisatoren",
            ),
        ),
    ]
