# Generated by Django 5.2.5 on 2025-08-25 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20250825_2127"),
        ("events", "0002_alter_event_organizer_eventorganizer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AfterPartyLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='z.B. "Bar Centrale", "Vereinsheim"',
                        max_length=100,
                        verbose_name="Name der Location",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Vollständige Adresse der Aftershow-Location",
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Breitengrad",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Längengrad",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Uhrzeit ab wann die Aftershow beginnt",
                        verbose_name="Beginn",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Was erwartet die Teams dort?",
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(
                        blank=True,
                        help_text="Telefon, Website, etc.",
                        verbose_name="Kontakt-Info",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="after_party",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aftershow-Location",
                "verbose_name_plural": "Aftershow-Locations",
            },
        ),
        migrations.CreateModel(
            name="GuestKitchen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='z.B. "Küche bei Familie Schmidt"',
                        max_length=100,
                        verbose_name="Name der Gastküche",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Vollständige Adresse der Gastküche",
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Breitengrad",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Längengrad",
                    ),
                ),
                (
                    "max_teams",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximale Anzahl Teams die diese Küche nutzen können",
                        verbose_name="Max. Teams",
                    ),
                ),
                (
                    "available_courses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Kurse für die diese Küche genutzt werden kann",
                        verbose_name="Verfügbare Kurse",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Zusätzliche Informationen zur Küche",
                        verbose_name="Notizen",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_kitchens",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "host_team",
                    models.ForeignKey(
                        help_text="Das Team das seine Küche zur Verfügung stellt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_guest_kitchens",
                        to="accounts.team",
                        verbose_name="Gastgeber-Team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gastküche",
                "verbose_name_plural": "Gastküchen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamGuestKitchenAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("appetizer", "Vorspeise"),
                            ("main_course", "Hauptgang"),
                            ("dessert", "Nachspeise"),
                        ],
                        max_length=20,
                        verbose_name="Kurs",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                (
                    "guest_kitchen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="using_teams",
                        to="events.guestkitchen",
                        verbose_name="Gastküche",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_kitchen_assignments",
                        to="accounts.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team-Gastküchen-Zuordnung",
                "verbose_name_plural": "Team-Gastküchen-Zuordnungen",
                "ordering": ["course", "assigned_at"],
                "unique_together": {("team", "course")},
            },
        ),
    ]
