# Generated by Django 5.2.5 on 2025-08-26 11:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_add_guest_kitchens_and_afterparty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="max_teams",
            field=models.PositiveIntegerField(
                help_text="Mindestens 3 Teams erforderlich",
                validators=[django.core.validators.MinValueValidator(3)],
                verbose_name="Minimale Team-Anzahl",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="price_per_person",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Preis pro Person",
            ),
        ),
    ]
