# Generated by Django 5.2.5 on 2025-08-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_max_teams_alter_event_price_per_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteGeometry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("start_lng", models.DecimalField(decimal_places=7, max_digits=10)),
                ("end_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("end_lng", models.DecimalField(decimal_places=7, max_digits=10)),
                ("distance", models.FloatField(help_text="Entfernung in km")),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Gehzeit in Minuten", null=True
                    ),
                ),
                (
                    "geometry_points",
                    models.JSONField(
                        help_text="Array von [lat, lng] Koordinaten für Leaflet"
                    ),
                ),
                ("point_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_api",
                    models.CharField(
                        default="osrm",
                        help_text="Verwendete API (osrm, openroute)",
                        max_length=50,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_geometries",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "start_lat", "start_lng"],
                        name="events_rout_event_i_5fd450_idx",
                    ),
                    models.Index(
                        fields=["event", "end_lat", "end_lng"],
                        name="events_rout_event_i_66ed7a_idx",
                    ),
                ],
                "unique_together": {
                    ("event", "start_lat", "start_lng", "end_lat", "end_lng")
                },
            },
        ),
    ]
