# Generated by Django 5.2.5 on 2025-08-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaryRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("allergy", "Allergie"),
                            ("intolerance", "Unverträglichkeit"),
                            ("diet", "Diät/Lebensstil"),
                            ("religion", "Religiöse Einschränkung"),
                        ],
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Leicht"),
                            ("moderate", "Moderat"),
                            ("severe", "Schwer"),
                            ("life_threatening", "Lebensbedrohlich"),
                        ],
                        default="mild",
                        max_length=20,
                        verbose_name="Schweregrad",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Zusätzliche Informationen zu dieser Einschränkung",
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "common_ingredients",
                    models.TextField(
                        blank=True,
                        help_text="Kommagetrennte Liste problematischer Zutaten",
                        verbose_name="Häufige problematische Zutaten",
                    ),
                ),
                (
                    "alternatives",
                    models.TextField(
                        blank=True,
                        help_text="Empfohlene Alternativen oder Ersatzstoffe",
                        verbose_name="Alternativen/Ersatzstoffe",
                    ),
                ),
                (
                    "emergency_info",
                    models.TextField(
                        blank=True,
                        help_text="Wichtige Informationen für Notfälle",
                        verbose_name="Notfall-Information",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ernährungseinschränkung",
                "verbose_name_plural": "Ernährungseinschränkungen",
                "ordering": ["category", "severity", "name"],
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="dietary_restrictions",
            field=models.TextField(
                blank=True,
                help_text="Weitere Details zu Allergien, Diäten, etc.",
                verbose_name="Zusätzliche Ernährungshinweise",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="dietary_restrictions_structured",
            field=models.ManyToManyField(
                blank=True,
                help_text="Wähle deine Allergien und Diäteinschränkungen aus",
                to="accounts.dietaryrestriction",
                verbose_name="Ernährungseinschränkungen",
            ),
        ),
    ]
