# Generated by Django 5.2.5 on 2025-08-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_dietaryrestriction_and_more"),
    ]

    operations = []
