# Generated by Django 5.2.5 on 2025-08-25 19:27

from django.db import migrations
from django.utils import timezone
from datetime import datetime


def create_additional_teams(apps, schema_editor):
    """Erstellt zusätzliche Teams und User für bessere Demo-Daten"""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    Team = apps.get_model('accounts', 'Team')
    TeamMembership = apps.get_model('accounts', 'TeamMembership')
    DietaryRestriction = apps.get_model('accounts', 'DietaryRestriction')
    Event = apps.get_model('events', 'Event')
    TeamRegistration = apps.get_model('events', 'TeamRegistration')

    # Hole Allergien
    allergien = {
        'nuss': DietaryRestriction.objects.filter(name='Nussallergie').first(),
        'gluten': DietaryRestriction.objects.filter(name='Glutenunverträglichkeit').first(),
        'laktose': DietaryRestriction.objects.filter(name='Laktoseintoleranz').first(),
        'veggie': DietaryRestriction.objects.filter(name='Vegetarisch').first(),
        'vegan': DietaryRestriction.objects.filter(name='Vegan').first(),
        'fisch': DietaryRestriction.objects.filter(name='Fischallergie').first(),
    }

    # Neue User und Teams
    additional_teams_data = [
        {
            'team_name': 'Die Kochprofis',
            'users': [
                {'username': 'michael_koch', 'first_name': 'Michael',
                    'last_name': 'Koch', 'email': 'michael.koch@email.de', 'allergies': []},
                {'username': 'nina_bauer', 'first_name': 'Nina', 'last_name': 'Bauer',
                    'email': 'nina.bauer@email.de', 'allergies': ['veggie']},
            ],
            'address': 'Leopoldstraße 45, 80802 München'
        },
        {
            'team_name': 'Schlemmer-Duo',
            'users': [
                {'username': 'felix_gross', 'first_name': 'Felix', 'last_name': 'Groß',
                    'email': 'felix.gross@email.de', 'allergies': ['gluten']},
                {'username': 'clara_wolf', 'first_name': 'Clara', 'last_name': 'Wolf',
                    'email': 'clara.wolf@email.de', 'allergies': ['laktose']},
            ],
            'address': 'Maximilianstraße 12, 80539 München'
        },
        {
            'team_name': 'Genuss-Freunde',
            'users': [
                {'username': 'david_schneider', 'first_name': 'David', 'last_name': 'Schneider',
                    'email': 'david.schneider@email.de', 'allergies': []},
                {'username': 'emma_richter', 'first_name': 'Emma', 'last_name': 'Richter',
                    'email': 'emma.richter@email.de', 'allergies': ['nuss']},
            ],
            'address': 'Sendlinger Straße 28, 80331 München'
        },
        {
            'team_name': 'Feinschmecker',
            'users': [
                {'username': 'lucas_hoffmann', 'first_name': 'Lucas', 'last_name': 'Hoffmann',
                    'email': 'lucas.hoffmann@email.de', 'allergies': ['vegan']},
                {'username': 'mia_wagner', 'first_name': 'Mia', 'last_name': 'Wagner',
                    'email': 'mia.wagner@email.de', 'allergies': []},
            ],
            'address': 'Rosenheimer Straße 143, 81671 München'
        },
        {
            'team_name': 'Küchen-Chaos',
            'users': [
                {'username': 'jonas_mueller', 'first_name': 'Jonas', 'last_name': 'Müller',
                    'email': 'jonas.mueller@email.de', 'allergies': ['fisch']},
                {'username': 'lena_huber', 'first_name': 'Lena', 'last_name': 'Huber',
                    'email': 'lena.huber@email.de', 'allergies': []},
            ],
            'address': 'Isarring 26, 81539 München'
        },
        {
            'team_name': 'Gaumen-Freude',
            'users': [
                {'username': 'tim_lehmann', 'first_name': 'Tim', 'last_name': 'Lehmann',
                    'email': 'tim.lehmann@email.de', 'allergies': []},
                {'username': 'anna_schulz', 'first_name': 'Anna', 'last_name': 'Schulz',
                    'email': 'anna.schulz@email.de', 'allergies': ['gluten', 'laktose']},
            ],
            'address': 'Theresienstraße 88, 80333 München'
        },
        {
            'team_name': 'Koch-Könige',
            'users': [
                {'username': 'paul_martin', 'first_name': 'Paul', 'last_name': 'Martin',
                    'email': 'paul.martin@email.de', 'allergies': ['veggie']},
                {'username': 'sophie_peters', 'first_name': 'Sophie', 'last_name': 'Peters',
                    'email': 'sophie.peters@email.de', 'allergies': []},
            ],
            'address': 'Augustenstraße 102, 80798 München'
        },
        {
            'team_name': 'Dinner-Detectives',
            'users': [
                {'username': 'robin_anderson', 'first_name': 'Robin', 'last_name': 'Anderson',
                    'email': 'robin.anderson@email.de', 'allergies': ['nuss', 'fisch']},
                {'username': 'lea_braun', 'first_name': 'Lea', 'last_name': 'Braun',
                    'email': 'lea.braun@email.de', 'allergies': []},
            ],
            'address': 'Goethestraße 31, 80336 München'
        },
        {
            'team_name': 'Hunger-Heroes',
            'users': [
                {'username': 'noah_zimmermann', 'first_name': 'Noah', 'last_name': 'Zimmermann',
                    'email': 'noah.zimmermann@email.de', 'allergies': []},
                {'username': 'julia_neumann', 'first_name': 'Julia', 'last_name': 'Neumann',
                    'email': 'julia.neumann@email.de', 'allergies': ['vegan']},
            ],
            'address': 'Prinzregentenstraße 75, 81675 München'
        }
    ]

    created_teams = []

    # Erstelle Teams
    for team_data in additional_teams_data:
        # Erstelle User
        team_users = []
        for user_data in team_data['users']:
            user = CustomUser.objects.create_user(
                username=user_data['username'],
                email=user_data['email'],
                password='testpass123',  # Passwort direkt bei create_user setzen
                first_name=user_data['first_name'],
                last_name=user_data['last_name'],
                phone_number=f'+49 151 {user_data["username"][-8:].upper()[:8]}',
                date_of_birth=timezone.make_aware(datetime(1990, 1, 1)).date(),
                dietary_restrictions=f'Individuelle Notizen für {user_data["first_name"]}',
                emergency_contact=f'{user_data["first_name"]} Notfall',
                emergency_phone='+49 151 NOTFALL',
                is_active=True
            )

            # Füge Allergien hinzu
            for allergy_key in user_data['allergies']:
                if allergien[allergy_key]:
                    user.dietary_restrictions_structured.add(
                        allergien[allergy_key])

            team_users.append(user)

        # Erstelle Team (contact_person ist der erste User)
        team = Team.objects.create(
            name=team_data['team_name'],
            description=f'Ein motiviertes Team aus München - {team_data["team_name"]}',
            home_address=team_data['address'],
            max_members=2,
            # Erster User ist Hauptansprechpartner
            contact_person=team_users[0],
            is_active=True
        )

        # Füge User zu Team hinzu
        for user in team_users:
            TeamMembership.objects.create(
                user=user,
                team=team,
                role='leader' if user == team_users[0] else 'member',
                is_active=True,
                joined_at=timezone.now()
            )

        created_teams.append(team)
        print(
            f'✅ Team "{team.name}" erstellt mit {len(team_users)} Mitgliedern')

    # Registriere alle neuen Teams für das Test-Event
    test_event = Event.objects.filter(name__icontains='München').first()
    if test_event:
        for team in created_teams:
            # Verschiedene Hosting-Präferenzen zuweisen
            hosting_preferences = [
                {'preferred_course': 'appetizer', 'can_host_appetizer': True,
                    'can_host_main_course': True, 'can_host_dessert': False},
                {'preferred_course': 'main_course', 'can_host_appetizer': False,
                    'can_host_main_course': True, 'can_host_dessert': True},
                {'preferred_course': 'dessert', 'can_host_appetizer': True,
                    'can_host_main_course': False, 'can_host_dessert': True},
                {'preferred_course': 'main_course', 'can_host_appetizer': True,
                    'can_host_main_course': True, 'can_host_dessert': True},
            ]

            idx = created_teams.index(team)
            prefs = hosting_preferences[idx % len(hosting_preferences)]

            registration = TeamRegistration.objects.create(
                event=test_event,
                team=team,
                registered_at=timezone.now(),
                status='confirmed',  # Direkt bestätigt für Demo
                preferred_course=prefs['preferred_course'],
                can_host_appetizer=prefs['can_host_appetizer'],
                can_host_main_course=prefs['can_host_main_course'],
                can_host_dessert=prefs['can_host_dessert'],
                payment_status='completed'
            )
            print(
                f'✅ Team "{team.name}" für Event registriert (Status: confirmed)')

    print(f'\n🎉 {len(created_teams)} zusätzliche Teams erstellt!')
    print(
        f'📊 Gesamt-Teams im Event: {TeamRegistration.objects.filter(event=test_event, status="confirmed").count() if test_event else "Event nicht gefunden"}')


def remove_additional_teams(apps, schema_editor):
    """Rollback - entfernt die zusätzlichen Teams"""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    Team = apps.get_model('accounts', 'Team')

    # Lösche User (Teams werden durch CASCADE gelöscht)
    additional_usernames = [
        'michael_koch', 'nina_bauer', 'felix_gross', 'clara_wolf',
        'david_schneider', 'emma_richter', 'lucas_hoffmann', 'mia_wagner',
        'jonas_mueller', 'lena_huber', 'tim_lehmann', 'anna_schulz',
        'paul_martin', 'sophie_peters', 'robin_anderson', 'lea_braun',
        'noah_zimmermann', 'julia_neumann'
    ]

    deleted_users = CustomUser.objects.filter(
        username__in=additional_usernames).delete()
    print(f'🗑️ {deleted_users[0]} User und zugehörige Teams gelöscht')


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20250825_2033"),
        # Stelle sicher, dass Event-Modell verfügbar ist
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_additional_teams, remove_additional_teams),
    ]
