# Generated by Django 5.2.5 on 2025-08-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20250825_2127"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="has_kitchen",
            field=models.BooleanField(
                default=True,
                help_text="Teams ohne Küche müssen Gastküchen nutzen wenn sie hosten",
                verbose_name="Hat eigene Küche",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="participation_type",
            field=models.CharField(
                choices=[
                    ("full", "Vollständige Teilnahme"),
                    ("kitchen_only", "Nur Gastküche anbieten"),
                    ("guest_only", "Nur als Gast (kein Hosting)"),
                ],
                default="full",
                help_text="Art der Teilnahme am Running Dinner",
                max_length=20,
                verbose_name="Teilnahme-Art",
            ),
        ),
    ]
