# Generated by Django 5.2.5 on 2025-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsession",
            name="preferred_transport_mode",
            field=models.CharField(
                choices=[
                    ("walking", "Zu Fuß"),
                    ("cycling", "Fahrrad"),
                    ("driving", "Auto"),
                    ("public_transport", "ÖPNV"),
                ],
                default="walking",
                max_length=20,
                verbose_name="Bevorzugtes Verkehrsmittel",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="transport_mode",
            field=models.CharField(
                choices=[
                    ("walking", "Zu Fuß"),
                    ("cycling", "Fahrrad"),
                    ("driving", "Auto"),
                    ("public_transport", "ÖPNV"),
                ],
                default="walking",
                max_length=20,
                verbose_name="Verkehrsmittel",
            ),
        ),
    ]
